# Generated by Django 5.0.6 on 2026-05-17 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReceipt',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_type', models.CharField(choices=[('IMPORT', 'Nhập kho'), ('EXPORT', 'Xuất kho')], max_length=10)),
                ('receipt_status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'inventory_receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('receipt', models.ForeignKey(db_column='receipt_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.inventoryreceipt')),
            ],
            options={
                'db_table': 'receipt_details',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product')),
                ('warehouse', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'inventory',
                'indexes': [models.Index(fields=['warehouse', 'product'], name='inventory_warehou_d4bfbf_idx')],
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
