# Generated by Django 5.0.6 on 2026-05-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('manager', 'Trưởng kho'), ('staff', 'Nhân viên kho')], default='staff', max_length=10),
        ),
    ]
